//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShawarmaRecipe
    {
        public int ShawarmaRecipeID { get; set; }
        public int ShawarmaID { get; set; }
        public int IngradientID { get; set; }
        public int Weight { get; set; }
    
        public virtual Ingradient Ingradient { get; set; }
        public virtual Shawarma Shawarma { get; set; }
    }
}
